"""Criação inicial das tabelas

Revision ID: bf2a9ab9cd08
Revises: 
Create Date: 2025-10-05 23:06:57.487775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2a9ab9cd08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('checklist_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leader_sector',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('checklist_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('operator_signature', sa.String(length=255), nullable=True),
    sa.Column('leader_signature', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_item_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_item_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('photo_evidence', sa.String(length=255), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('item_template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['checklist_instance.id'], ),
    sa.ForeignKeyConstraint(['item_template_id'], ['checklist_item_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_item_response')
    op.drop_table('checklist_item_template')
    op.drop_table('checklist_instance')
    op.drop_table('leader_sector')
    op.drop_table('checklist_template')
    op.drop_table('user')
    op.drop_table('sector')
    # ### end Alembic commands ###
